plugins {
    id 'buildlogic.java-application-conventions'
}

application {
    mainClass = 'engine.CliEngine'
}

run {
    standardInput = System.in
}

dependencies {
    implementation project(':com.ingsis.common')
    implementation project(':com.ingsis.charstream')
    implementation project(':com.ingsis.lexer')
    implementation project(':com.ingsis.parser')
    implementation project(':com.ingsis.interpreter')
    implementation project(':com.ingsis.formatter')
    implementation project(':com.ingsis.sca')
}